# GitHub Repo Metadata (for raufA1/raufA1)
repository:
  name: raufA1
  description: "AI-native developer | Building AI-powered tools: Smart CLI, ClipFlow, LLM Family Pack | Open-source enthusiast"
  homepage: https://github.com/raufA1
  topics: >
    ai,
    ai-native,
    multi-agent-systems,
    llm,
    generative-ai,
    developer-tools,
    automation,
    cli,
    fastapi,
    docker,
    github-actions,
    video-automation,
    youtube-shorts,
    instagram-reels,
    content-automation,
    open-source,
    productivity,
    devops,
    postgresql,
    redis